[package]
name = "gtfs-guru-model"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
